project:
  type: book
  output-dir: docs

book:
  title: "MATH 3503 - Winter 2025"
  author: "Joey Bernard"
  date: "2024-07-05"
  chapters:
    - index.qmd
    - intro.qmd
    - First Order ODEs.qmd
    - Second Order ODEs.qmd
    - Systems of ODEs.qmd
    - Fourier Series.qmd
    - Laplace Transforms.qmd
    - summary.qmd

format:
  html:
    theme: cosmo
  pdf:
    documentclass: report
    keep-tex: true


