# Second Order ODEs

Second order ODEs are differential equations where we may have second derivatives of y with respect to x. The general form looks like

$A(x) y^{''} + B(x) y^{'} + C(x) y = F(x)$

Usually, we divide through so that the $y^{''}$ term is all by itself. If we do this, we end up with

$y^{''} + p(x) y^{'} + q(x) y = f(x)$



## Homogeneous with Constant Coefficients

The first class of second order ODEs we will look at are homogeneous equations. This is the special case of setting $f(x) = 0$. We will also further constrain the equations for this section by only looking at constant coefficients. This special case looks like

$y^{''} + b y^{'} + c y = 0$

In the most general case, there should be two linearly independent solutions ($y_1 and y_2$) that combine to make the general solution. This general solution looks like

$y = C_1 y_1 + C_2 y_2$

You can check for linear independence by using the Wronskian. If we have linear independence, then we have

$\begin{vmatrix}
y_1 & y_2 \\
y^{'}_1 & y^{'}_2
\end{vmatrix} \ne 0$

In order to find these two solutions to the differential equation, we start by setting up the characteristic equation that is associated with the differential equation. This characteristic equation is given by

$a r^2 + b r + c = 0$

We can then find out what the two values for r are. Because this is just a quadratic equation, it is simply

$r_1,r_2 = \frac{-b \pm \sqrt{b^2 - 4 a c}}{2 a}$

There are three cases when solving for r.

\begin{itemize}
\item Case 1 - $r_1$ and $r_2$ are real and unique
\item Case 2 - $r_1$ and $r_2$ are equal
\item Case 3 - $r_1$ and $r_2$ are complex
\end{itemize}

### Case 1

If we have case 1, we can easily construct our solution. In this case, it would look like

$y = C_1 e^{r_1 x} + C_2 e^{r_2 x}$

### Case 2

If we have case 2, we can't simply use the same method as for case 1. We would end up with two equal equations. In this case, we can separate $y_1$ and $y_2$ by multiplying one of them by x. This would give us the solution

$y = C_1 e^{r x} + C_2 x e^{r x}$

### Case 3

Case 3 is a new one if you have never considered the imaginary case for the quadratic equation. In this case, the solution to the characteristic equation is

$r_{1,2} = \alpha \pm \beta i$

In this case, we use the real and imaginary parts of r to make up our solution for y. The general form becomes

$y = C_1 e^{\alpha x} cos(\beta x) + C_2 e^{\alpha x} sin(\beta x)$



## Initial Value Problem

In all of the above cases, we would have constants of integration that would show up in the solutions. In the first order ODE case, a single initial value is enough to define the constant of integration that appears. In the second order case, we will need two initial values. These take the form of

$y(x_0) = y_0 \\
y^{'}(x_0) = y^{'}_0$

These can be plugged into the general solution for y to find a particular solution.



## Non-homogeneous Differential Equations with Constant Coefficients

Up to now, we have been working with homogeneous equations where f(x)=0. In many physical situations, we end up with a non-homogeneous differential equation. The f(x) term is often called a driving function or forcing function.

In order to solve these types of equations, we start by assuming that the equation is homogeneous. In this way, we can find a complimentary solution, $y_c$ that solves the equation when we pretend that f(x)=0. The second step is to come up with a second solution, $y_p$, called the particular solution. We will look at two options of finding this particular solution.

### Undetermined Coefficients

The first method is to use the method of undetermined coefficients. The first step is to find $y_c$. This is done by assuming that the ODE is actually homogeneous, or of the form

$a y^{''} + b y^{'} + c y = 0$

In this case, we can set up a characteristic equation that is associated with the homogeneous version of our ODE.

$a r^2 + b r + c = 0$

We now need to solve for the values of r, using this basic quadratic equation. The solution is given by

$r = \frac{-b \pm \sqrt{b^2 - 4 a c}}{2 a}$

This gives us three cases for possible values of r.

#### Case 1
In this case, both values of r are real and unique. For this case, we have a solution of y given by

$y = C_1 e^{r_1 x} + C_2 e^{r_2 x}$

#### Case 2
In this case, r is real, but both values are equal. In this case, we need to adjust one of the possible terms for y so that everything stays linearly independent. We then get

$y = C_1 e^{r x} + C_2 x e^{r x}$

#### Case 3
In this case, we end up with complex values for r, of the form

$r = \alpha \pm \beta i$

This leads to solutions for y as given by

$y = C_1 e^{\alpha x} cos(\beta x) + C_2 e^{\alpha x} sin(\beta x)$

Once we have this solution for the homogeneous version, we need to find the extra part to account for the right hand side of the equation, f(x). This extra part is called the driving function or forcing function. We actually make a guess based on the form of f(x). The table below covers the standard types of f(x) that we tend to run into.

| $f(x)$ | $y_p$ |
|--------|-------|
| $a x + b$ | $A x + B$ |
| $a x^2 + b x + c$ | $A x^2 + B x + C$ |
| $a sin(b x)$ | $A sin(b x) + B cos(b x)$ |
| $a cos(b x)$ | $A cos(b x) + B sin(b x)$ |
| $a e^{b x}$ | $A e^{b x}$ |
| $(a x + b) e^{c x}$ | $(A x + B) e^{c x}$ |
| $a e^{b x} sin(c x)$ | $A e^{b x} sin(c x) + B e^{b x} cos(c x)$|
| $(a x^2 + b x + c) e^{d x} cos(\pi x)$ | $(A x^2 + B x + C) e^{d x} cos(\pi x) + (D x^2 + E x + F) e^{d x} sin(\pi x)$ |
| $a x + e^{b x}$ | $A x + B + C e^{b x}$ |
| $a + e^{b x}$ | $A + B e^{b x}$ |
| $a e^{b x} + c sin(d x)$ | $A e^{b x} + C sin(d x) + D cos(d x)$ |
| $a x^2 + b cos(c x)$ | $A x^2 + B x + C + D cos(c x) + E sin(c x)$ |

In order to find the coefficients, you would take the first and second derivatives of your guess and plug it into the origianl equation in question. Setting this equal to f(x), you can then compare terms from the left hand side to the equivalent terms on the right hand side to find each of the coefficients. This then gives you the $y_p$ part of the general solution.

*NOTE* - You need to make sure that $y_c$ and $y_p$ are linearly independent. If they aren't, you can multiply $y_p$ by some power of x in order to make the solutions linearly independent.


### Variation of Parameters

In order to use variation of parameters, you start the same way as above to find the $y_c$ solution. Once you have that, you will have two partial solutions $y_1$ and $y_2$, since we have

$y_c = C_1 y_1 + C_2 y_2$

The second solution is given by

$y_p = u_1 y_1 + u_2 y_2$

In order to find $u_1$ and $u_2$, we use the following formulas:

$u_1^{'} = \frac{
\begin{vmatrix}
0 & y_2 \\
f(x) & y_2^{'}
\end{vmatrix}}{\begin{vmatrix}
y_1 & y_2 \\
y_1^{'} & y_2^{'}
\end{vmatrix}}$

and

$u_2^{'} = \frac{
\begin{vmatrix}
y_1 & 0 \\
y_1^{'} & f(x)
\end{vmatrix}}{\begin{vmatrix}
y_1 & y_2 \\
y_1^{'} & y_2^{'}
\end{vmatrix}}$

Once you integrate these to get $u_1$ and $u_2$, you can plug them back into $y_p$.


